### ISSUE TITLE
[Feature Request]: Add align support for YAML indentation mode

### ISSUE THREAD

**Issue by rytswd** [upsidr/importer#25]
### 🔮 Relevant Command

importer update, importer generate

### 🗂 Language Type

YAML

### 🔎 Request Details

When using Importer Marker with indentation mode, we should allow aligning the indentation by preceding spaces to the Importer Marker. This makes it easier than using absolute indentation and counting number of spaces.

Before:

```yaml
spec:
  template:
    metadata:
      # == imptr: app-metadata / begin from: ./some-target.yaml indent: absolute 6 ==
      # == imptr: app-metadata / end ==
```

After:

```yaml
spec:
  template:
    metadata:
      # == imptr: app-metadata / begin from: ./some-target.yaml indent: align ==
      # == imptr: app-metadata / end ==
```
