### ISSUE TITLE
[Feature Request]: Support YAML indentation to work with non-space characters

### ISSUE THREAD

**Issue by rytswd** [upsidr/importer#58]
### 🔮 Relevant Command

importer update, importer generate

### 🗂 Language Type

YAML

### 🔎 Request Details

Currently, with the following YAML:

```yaml
some-array:
  - # == i: import-some-data / begin from: ./abc.yaml#[abc] indent: align ==
    # == i: import-some-data / end ==
    other-key: other-value
```

The preceding indentation is not handled, and thus you would end up with

```yaml
some-array:
  - # == i: import-some-data / begin from: ./abc.yaml#[abc] indent: align ==
abc: abc
    # == i: import-some-data / end ==
    other-key: other-value
```

If the indentation handling simply checks how many characters there are, we should be able to get the following

```yaml
some-array:
  - # == i: import-some-data / begin from: ./abc.yaml#[abc] indent: align ==
    abc: abc
    # == i: import-some-data / end ==
    other-key: other-value
```

This should allow better handling of list notation in YAML like shown above.
