### ISSUE TITLE
[Bug]: Importer Generate removes data that should not be removed

### ISSUE THREAD

**Issue by rytswd** [upsidr/importer#63]
### 🔖 Version

v0.0.1-rc19

### 📌 What happened?

With YAML input, Importer can now handle this

```yaml
some-list:
  - # == i: import / begin from: ./a.yaml#[a] indent: align ==
    # == i: import / end ==
```

With `importer update`, this will be correctly handled such that

```yaml
some-list:
  - # == i: import / begin from: ./a.yaml#[a] indent: align ==
    a: a
    description: abc
    # == i: import / end ==
```

But with `importer generate`, this ends up with the following

```yaml
some-list:
    a: a
    description: abc
```

This is because the Importer Generate tries to strip off markers, and it was naïve to remove the line when marker is found. When marker has non-whitespace character on the same line, Importer Generate should not remove the entire line, but remove only the marker.
